### ISSUE TITLE
Pie Charts and Trend Lines

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#17]
I want to see Pie Charts and Trend lines based on my map extent and filters

**Comment by steveoh** [comment]
What data do you want to highlight in these trend lines and pie charts?

**Comment by brigsz** [comment]
I think the trend lines and pie charts should closely follow the user filter selection, but not every filter can produce a trend line or a pie chart, well or one that makes sense.  I need to speak with the client on this.

**Comment by brigsz** [comment]
I would like 6 graphics showing accident counts by the following;
1.  type of `Contributing Factors`
2.  type of`Weather` condition
3.  type of `Driver Distraction`
4.  type of `Road Conditions`
5. `Days of the week`
6. `Time of day` (start with hour, if unwieldy then 3 hour blocks) 

These would be generated each time and would show all results unless a user sets a constraint.

**Comment by steveoh** [comment]
Any chance of a quick mockup for what that would look like @brigsz?

**Comment by brigsz** [comment]
Let me put my artist fingers to work

**Comment by brigsz** [comment]
![img_0531](https://cloud.githubusercontent.com/assets/6306463/6968116/6132081a-d921-11e4-9a85-32d288053c04.JPG)
![img_0532](https://cloud.githubusercontent.com/assets/6306463/6968122/659d5df0-d921-11e4-898d-ba7c6c529033.JPG)

**Comment by brigsz** [comment]
I have edited a comment just above your request for a mock up.  That is a listing of the graphics.  I thought of making a simple mock up like I had before, was that helpful at all?  Each of the 6 requested graphics probably has an optimal way in which the information should be portrayed.

**Comment by steveoh** [comment]
These will all be pie charts do you think?

**Comment by brigsz** [comment]
I think 3d donuts, pie charts and fixed placement columns may be the answer.  I think fixed placement columns could work for days of the week.  Times of the day is a little harder for me to visualize.  especially in 1 hour blocks.  3 hour blocks could be a fixed placement column...

**Comment by steveoh** [comment]
can you link to those?

**Comment by brigsz** [comment]
1. http://www.highcharts.com/demo/3d-pie-donut/sand-signika
2. http://www.highcharts.com/demo/pie-basic/sand-signika
3. http://www.highcharts.com/demo/column-placement/sand-signika

**Comment by steveoh** [comment]
yes I liked the mockup you had before. I'm not sure which type of chart to use for which set of data.
