### ISSUE TITLE
Filter Results Comparison

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#18]
I want a way to compare the results of two filters

**Comment by brigsz** [comment]
I would like to have the system hold my search parameters and just force me to change the date and time

**Comment by steveoh** [comment]
would you send this for UI/UX work?

**Comment by steveoh** [comment]
https://drive.google.com/a/utah.gov/folderview?id=0ByBPl4Mwaw9Ibm52MXZoZlpGbUk&usp=sharing
