### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#19]
The following Logos should appear on the site.

**Very Visible**
Utah Highway Patrol
UDOT
UDPS
**Much Smaller**
AGRC

**Comment by steveoh** [comment]
Do you have the images?

**Comment by brigsz** [comment]
![uhp_logo](https://cloud.githubusercontent.com/assets/6306463/6258422/9ad9f9fa-b785-11e4-8287-124d1271288d.png)
![dps_logo](https://cloud.githubusercontent.com/assets/6306463/6258424/a02bbe98-b785-11e4-8832-03c886555896.png)

**Comment by brigsz** [comment]
![udot_logo_high_rgb](https://cloud.githubusercontent.com/assets/6306463/6259149/c00a05c4-b78c-11e4-8438-fc5dba164ed1.png)
