### ISSUE TITLE
Location Search

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#2]
1. I need to search by route and a to and from milepost
2. I need to search by a UHP section 
3. I need to do a freehand polygon search on the map

1, 2, and 3 are mutually exclusive.

![locationsearch](https://cloud.githubusercontent.com/assets/6306463/5728980/fcf0f79a-9b2b-11e4-9bb2-1ff66fbef257.png)

**Comment by steveoh** [comment]
Can you provide a list of UHP sections or how to get at them?

**Comment by brigsz** [comment]
Yes, they are in SGID10.Society.UHPFieldSections

**Comment by brigsz** [comment]
I believe we should take out UHP section as a search criteria for this public app.  I will check

**Comment by steveoh** [comment]
@brigsz milepost query....
1. There is a milepost and route-number field that we could use
2. Use the route and milepost tool from PEL and buffer it by some distance to make it a polygon instead of a line.

What _route_ do you want to take?

**Comment by brigsz** [comment]
Please use the route and milepost from the data, not the widget from PEL
