### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#23]
As a user moves from Time and Date Factors, to Spatial Factors to Crash Severity all those choices are "AND"  except Weather Condition Factor should be "OR".

**Comment by steveoh** [comment]
So to clarify,

If in the date time I choose `monday`, `tuesday` they should be joined with an `AND`?

Then if I add more filters from spatial factors, weather, or severity, they should then be joined together with `AND`.

But the weather **items** should be joined together with `OR`?

**Comment by brigsz** [comment]
Yes, it doesn't seem logical to choose both `Snow` and `Rain`
