### ISSUE TITLE
Accident Counts on charts

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#25]
I would like to see both the accident # and also the % of accidents that fit the criteria

**Comment by steveoh** [comment]
This only makes sense for pie charts right? Or do you want it for all?

**Comment by brigsz** [comment]
Is this complete for pie charts?

**Comment by steveoh** [comment]
No I do not think so. I forgot about it.

**Comment by steveoh** [comment]
closed by c840226e39c941b17e35a2f4573762e91ecff0d6
