### ISSUE TITLE
Search by County

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#26]
I would like to be able to search by one or more counties. This should be located in the spatial factors section and should be placed above the route and milepost search.

**Comment by steveoh** [comment]
```
NULL
84120
AMALGA
BEAVER
BLUFFDALE
BOUNTIFUL
BOX ELDER
CACHE
CARBON
CLEARFIELD
COTTONWOOD HEIGHTS
DAGGETT
DAVIS
DRAPER
DUCHESNE
EMERY
EXIT #99
GARFIELD
GENOLA
GRAND
GRANTSVILLE
HOLLADAY
HURRICANE
IRON
JUAB
KANAB
KANE
KAYSVILLE
LAYTON
LAYTON UT
LEHI
MIDVALE
MILLARD
MORGAN
MURRAY
OF EXIT 9
OGDEN
OREM
OUTSIDE CITY LIMITS
PARK CITY
PERRY
PIUTE
RICH
RIVERTON
ROOSEVELT
SALT LAKE
SALT LAKE CITY
SAN JUAN
SANDY
SANPETE
SARATOGA SPRINGS
SEVIER
SOUTH JORDAN
SOUTH SALT LAKE
ST. GEORGE
SUMMIT
SUNSET
TAYLORSVILLE
THAT
TOOELE
U
UINTAH
UNINCORPORATED
UT
UTAH
UTM840
WASATCH
WASHINGTON
WAYNE
WEBER
WEST VALLEY
WEST VALLEY CITY
WILLARD
```

These are the values in their table. I should probably fix that in the etl script some how or should I let them deal with their data?

**Comment by brigsz** [comment]
I think we need to do both. I will alert them to their data.

On Apr 30, 2015, at 5:34 PM, steveoh notifications@github.com wrote:

NULL
84120
AMALGA
BEAVER
BLUFFDALE
BOUNTIFUL
BOX ELDER
CACHE
CARBON
CLEARFIELD
COTTONWOOD HEIGHTS
DAGGETT
DAVIS
DRAPER
DUCHESNE
EMERY
EXIT #99
GARFIELD
GENOLA
GRAND
GRANTSVILLE
HOLLADAY
HURRICANE
IRON
JUAB
KANAB
KANE
KAYSVILLE
LAYTON
LAYTON UT
LEHI
MIDVALE
MILLARD
MORGAN
MURRAY
OF EXIT 9
OGDEN
OREM
OUTSIDE CITY LIMITS
PARK CITY
PERRY
PIUTE
RICH
RIVERTON
ROOSEVELT
SALT LAKE
SALT LAKE CITY
SAN JUAN
SANDY
SANPETE
SARATOGA SPRINGS
SEVIER
SOUTH JORDAN
SOUTH SALT LAKE
ST. GEORGE
SUMMIT
SUNSET
TAYLORSVILLE
THAT
TOOELE
U
UINTAH
UNINCORPORATED
UT
UTAH
UTM840
WASATCH
WASHINGTON
WAYNE
WEBER
WEST VALLEY
WEST VALLEY CITY
WILLARD

These are the values in their table. I should probably fix that in the etl
script some how or should I let them deal with their data?
