### ISSUE TITLE
Valid Time Range for Data

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#27]
I would like it stated somewhere the date range of the data

**Comment by steveoh** [comment]
let's send this to UI/UX folks also

**Comment by brigsz** [comment]
Did we receive anythig from terry on this one?

**Comment by brigsz** [comment]
Is it something you can just put this above the chart section

**Comment by steveoh** [comment]
No, we never did. I don't think it belongs on the charts but I can push it somewhere

**Comment by brigsz** [comment]
Yah, probably just in the main page

On Jun 17, 2015, at 4:17 PM, steveoh notifications@github.com wrote:

No, we never did. I don't think it belongs on the charts but I can push it
somewhere
