### ISSUE TITLE
Severity Parameters of a Crash

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#3]
There are 3 severity choices, mutually exclusive of each other
1. No Injuries
2. Injuries
3. Fatal

![severity](https://cloud.githubusercontent.com/assets/6306463/5729118/14ac3b78-9b2d-11e4-902d-fe8e7cf7d4b4.png)

**Comment by steveoh** [comment]
Mutually exclusive things would usually be represented with a radio box since only one can be selected where as checkboxes all can be selected. Just a prototyping heads up for the future @brigsz

**Comment by brigsz** [comment]
This one is no longer valid
