### ISSUE TITLE
Date Comparison

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#30]
I would like to see my initial search and my comparison search on the same summary report page

**Comment by brigsz** [comment]
I think this is just a printout of the charting.

**Comment by steveoh** [comment]
Can we use a print.css and have them use the printer? Turning this into a pdf or something of that sort server side would be... challenging.

**Comment by brigsz** [comment]
That must of what we spoke about.

Yes, we should take the easy route

On Jun 17, 2015, at 4:24 PM, steveoh notifications@github.com wrote:

Can we use a print.css and have them use the printer? Turning this into a
pdf or something of that sort server side would be... challenging.

**Comment by steveoh** [comment]
closed by 72fed014db635d7bc9d8b6715dfe6149488b1574
