### ISSUE TITLE
Add m to route and mile post query

### ISSUE THREAD

**Issue by steveoh** [agrc/Crash-web#35]
route_type column

m = mainline, r = ramp, x=other, c = collector

**Comment by steveoh** [comment]
route_type is not in the source data. add this to the list of new data to grab.

**Comment by BGranberg** [comment]
The 6th character in UDOT route ID's can carry a route type. If there is no route type it is a mainline.

For example 0015PR31204 is a ramp #04 at milepost 213. 

for mainlines, there may be a subset. if first character is 0 then it is a main highway if it is 1,2,or 3 it is a FAE local road

**Comment by steveoh** [comment]
Thanks @BGranberg. This is already stored in the data so it is much easier than what you are describing.
