### ISSUE TITLE
Cull through contributing factors

### ISSUE THREAD

**Issue by steveoh** [agrc/Crash-web#36]
New restraint seatbelt column
add unrestrained to contributing factor

maybe remove overturn or roll.

**Comment by brigsz** [comment]
Add Speed as a contributing factor as well.

**Comment by steveoh** [comment]
so the contributing factors are from the rollups table, is the speed that you want also a new column or do you want the results to be built from the contributing cause and alternate cause columns with the value `Exceeded Posted Speed Limit` from the drivers table to be used?

**Comment by steveoh** [comment]
looks like we already answered that question with the commit
