### ISSUE TITLE
Factors of a Crash

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#4]
I want to be able to pick some high level factors, I should be allowed to pick more than one.

Wild Animal Involved
Domestic Animal Involved
Pedestrian Involved
Bicyclist Involved
Motorcycle Involved
Overturn/Rollover
Commercial Motor Vehicle
Improper Restraint
Teenage Driver
Older Driver
DUI
Intersection Related
Night/Dark Condition

![factors](https://cloud.githubusercontent.com/assets/6306463/5729183/9c05a0e6-9b2d-11e4-849d-4c36e85ce33e.png)

**Comment by brigsz** [comment]
As a user I should be able to choose any or all of them, I don't think there are two mutually exclusive, but Teenage driver and Older driver do not seem to be compatible.

**Comment by steveoh** [comment]
If you could clarify that last statement that would be great.

**Comment by brigsz** [comment]
I was trying to look at the list and think if you would ever pick both teenage driver and Older driver at the same time.

**Comment by brigsz** [comment]
I would say to keep it simple, just let a person pick all, none or some.

**Comment by steveoh** [comment]
Thanks, I definitive answers are best.
