### ISSUE TITLE
Bar Charts, Contributing factors

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#41]
When you have ran a comparison and you choose bar chart for contributing factors, the bar chart does not show all contributing factors for both the original and secondary choices.

**Comment by steveoh** [comment]
The original query may have a:1 and b:2 where as the secondary query might have a:3 and c:4. Is this what you are seeing?

**Comment by brigsz** [comment]
I am afraid you have lost me on that one.

**Comment by steveoh** [comment]
The categories and associated data for each need to be present in both series. Otherwise line and bar charts tell big lies.

**Comment by brigsz** [comment]
Okay, maybe line and bar are against the rules?

**Comment by steveoh** [comment]
i think i can make the api output the data this way.
