### ISSUE TITLE
#s and Circles not drawing on the base map in production

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#44]
The Request URL is http://crashmapping.utah.gov/app/resources/http//fonts.gstatic.com/s/opensans/v10/cJZKeOuBrn4kERxqtaUH3ZBw1xU1rKptJj_0jans920.woff2

It responds with a 404 Not Found

Production is http://crashmapping.utah.gov

**Comment by BGranberg** [comment]
Maybe we should build in some functionality into our sites where a non
developer at agrc could flip a switch that would force a "Site currently
experiencing technical difficulties: please check back later" message? Just
something to think about?

On Thu, Oct 15, 2015 at 8:58 AM, Matt Peters notifications@github.com
wrote:

> The Request URL is
> http://crashmapping.utah.gov/app/resources/http//fonts.gstatic.com/s/opensans/v10/cJZKeOuBrn4kERxqtaUH3ZBw1xU1rKptJj_0jans920.woff2
> 
> It responds with a 404 Not Found
> 
> Production is http://crashmapping.utah.gov
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/Crash-web/issues/44.

## 

Bert Granberg, Director
Utah Automated Geographic Reference Center (AGRC)
1 State Office Bldg, Rm 5130
Salt Lake City, UT 84114
bgranberg@utah.gov
801 538-3163 (o)
801 558 3563 (m)

**Comment by steveoh** [comment]
woff2 will always 404. point.json is what is missing for some reason. I can't vpn from the airport so I will check it out tomorrow.

**Comment by brigsz** [comment]
Ha! Thanks! Yes, trying my debug skills in chrome.

On Oct 18, 2015, at 2:47 PM, steveoh notifications@github.com wrote:

woff2 will alway 404. point.json is what is missing for some reason.

**Comment by steveoh** [comment]
DTS fouled up and broke our database connection string.
