### ISSUE TITLE
Crash Severity No Injury and Injury filters are broken

### ISSUE THREAD

**Issue by wsjones** [agrc/Crash-web#47]
When clicking on 'No Injury' or 'Injury' and then 'Apply' no crashes are displayed on the map.

Further info, if needed:
No Injury is defined as CRASH_SEVERITY_ID = 1
Injury is defined as CRASH_SEVERITY_ID = 2, 3, OR 4
Fatal is defined as CRASH_SEVERITY_ID = 5

**Comment by steveoh** [comment]
The code is using `None Non-Fatal Fatal` for it's values when the database is using `No Injury, Injury, Fatal`. This was made to the db seeder in [July](https://github.com/agrc/Crash-db/commit/2f0afd9c7dcc1ae7aa29219f8d364d6ba1485f00) and [partially fixed](4644bbd16da0e66cb11f08a026f42eb99bf7e145) in the web app. I can push a new fix out hopefully tomorrow.

**Comment by steveoh** [comment]
fixed in `1.0.1`
