### ISSUE TITLE
Contributing Factors of a Crash

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#5]
I should be able to include one or more of the following

Weather
Road Conditions
Driver Contributing Factor 1
Driver Contributing Factor 2
Driver Condition
Driver Distraction
Driver Age

![contributingfactors](https://cloud.githubusercontent.com/assets/6306463/5729270/77e93d34-9b2e-11e4-8d1c-f78cc181b9db.png)

**Comment by brigsz** [comment]
As a user I should be able to choose all, some, or none of these choices

**Comment by steveoh** [comment]
This doesn't make sense. These factors are not boolean. For instance, every crash has [road conditions](https://github.com/agrc/Crash-db/blob/b98f51e5b332ce39e48567dfdaaad10206c713a3/src/dbseeder/models.py#L338-L346) and [weather conditions](https://github.com/agrc/Crash-db/blob/b98f51e5b332ce39e48567dfdaaad10206c713a3/src/dbseeder/models.py#L322-L330). I think this needs to be redesigned.
