### ISSUE TITLE
Ongoing update issues

### ISSUE THREAD

**Issue by wsjones** [agrc/Crash-web#53]
1) Date range not updating with the weekly update process.
2) Fix of the Contributing Factors filters not working again with the weekly update process.

**Comment by steveoh** [comment]
Are you still adding new data to this application?

**Comment by wsjones** [comment]
I loaded new data files on Friday.  Looks like the data updated on the
website, but the "Data available" date range notification at the top of the
page did not update.

Scott

**Comment by steveoh** [comment]
I'm going to close this since I revamped the update script. Please comment here and reopen after you upload new data or we see another issue.
