### ISSUE TITLE
Coordinate columns labeled Latitude and Longitude but hold data in UTM (mostly).

### ISSUE THREAD

**Issue by jacobdadams** [agrc/Crash-web#60]
The CSV from the "Download Application Data" link uses columns titled "GPS_LATITUDE" and "GPS_LONGITUDE" to hold the UTM y and x values. The Data Origination section explains that its in UTM Zone 12N NAD83, but some users are thrown off by having "latitude" and "longitude" in the field names. Can these names be changed to something like "UTM_Y" and "UTM_X", or are they set by the data provider?

**Comment by steveoh** [comment]
They are set by the data provider

**Comment by jacobdadams** [comment]
Yeah, I figured that might be the case. Just wanted to pass along what I'd
heard from users.

**Comment by steveoh** [comment]
You could approach clancy black about it.
