### ISSUE TITLE
Popups Broken

### ISSUE THREAD

**Issue by kcoburndnr** [agrc/Crash-web#61]
Hi! 
I wanted to let you know that the popups no longer work on the following application. 
https://crashmapping.utah.gov/
![image](https://user-images.githubusercontent.com/57368593/68147739-fc9c7500-fef7-11e9-8e02-5e8821baff43.png)
![image](https://user-images.githubusercontent.com/57368593/68147805-18a01680-fef8-11e9-814d-8e845a3b91ab.png)
Thank you!

**Comment by steveoh** [comment]
Thank you for the bug report. We're in the process of sorting out a data sharing issue and I hope to have this resolved this week. I will keep everyone posted with this issue. Thanks for the report.

**Comment by steveoh** [comment]
this issue is now resolved.

**Comment by kcoburndnr** [comment]
Thanks! It all works for me as it used too. 

Thanks again for getting on it so quickly!
