### ISSUE TITLE
Production DNS swap

### ISSUE THREAD

**Issue by steveoh** [agrc/Crash-web#68]
I believe that the cloud crash is ready to be used in production.

**Comment by nathankota** [comment]
* [x]  (INC1501893) Add `crashmapping.utah.gov` to the firebase project `ut-dts-agrc-crash-prod` 
 * [x]  Update the existing DNS (crashmapping.utah.gov) to point to the firebase project DNS records instead of the on prem web server.

**Comment by nathankota** [comment]
resolved via INC1501893 and INC1501926
