### ISSUE TITLE
Contributing Factors

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#9]
As a Public User the following filter choices should be presented to me;

**Tier 1**
1. Follow to close
2. Speed
3. Drowsy
4. Aggressive
5. Failed to Yield
6. Seatbelt
7. Distraction
8. DUI 

**Tier 2**
1. Pedestrian
2. Bicycle
3. Motorcycle
4. Animal (domestic and wild)

**Comment by steveoh** [comment]
I don't understand tier 1 and tier 2.
